import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Navbar";
import SessionProviderAuth from "./signin/sessionProviderAuth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviderAuth>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </SessionProviderAuth>
    </html>
  );
}
